// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHT9IOCbWg4skap2Hr4Rx7GkzIPxIHb9s',
    appId: '1:669358768813:web:526ff02264f29d46e13c24',
    messagingSenderId: '669358768813',
    projectId: 'barkbuddy-ai',
    authDomain: 'barkbuddy-ai.firebaseapp.com',
    storageBucket: 'barkbuddy-ai.appspot.com',
    measurementId: 'G-EW8NDD7B2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI2OQM1lCOjPMVTVEg369R8Zvw7Q2wmcg',
    appId: '1:669358768813:android:a242827ef26602eae13c24',
    messagingSenderId: '669358768813',
    projectId: 'barkbuddy-ai',
    storageBucket: 'barkbuddy-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzdi02OMZyB-e513DsGrbBS1euKCnxl6E',
    appId: '1:669358768813:ios:fcac04da1b958ecee13c24',
    messagingSenderId: '669358768813',
    projectId: 'barkbuddy-ai',
    storageBucket: 'barkbuddy-ai.appspot.com',
    iosBundleId: 'com.example.barkbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzdi02OMZyB-e513DsGrbBS1euKCnxl6E',
    appId: '1:669358768813:ios:fcac04da1b958ecee13c24',
    messagingSenderId: '669358768813',
    projectId: 'barkbuddy-ai',
    storageBucket: 'barkbuddy-ai.appspot.com',
    iosBundleId: 'com.example.barkbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHT9IOCbWg4skap2Hr4Rx7GkzIPxIHb9s',
    appId: '1:669358768813:web:8bba992dfe50fe83e13c24',
    messagingSenderId: '669358768813',
    projectId: 'barkbuddy-ai',
    authDomain: 'barkbuddy-ai.firebaseapp.com',
    storageBucket: 'barkbuddy-ai.appspot.com',
    measurementId: 'G-S89DSSGSCN',
  );
}

extension VapidSupport on FirebaseOptions {
  String get vapidKey => "BHm_VapnTDJCgqH_pboKrHHVQuu2Kc2yEbGVBcT_sW7cATnu_aVC_yDb087X76jKfpUfde4-v3Ntj_tr4Ma2dZ0";
}