// Flutter icons Barkbuddy
// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class BarkbuddyIcons {
  BarkbuddyIcons._();

  static const _kFontFam = 'barkbuddy-icons';
  static const String? _kFontPkg = null;

  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xf6d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
