// Flutter icons MyFlutterApp
// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
// This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  MyFlutterApp
//      fonts:
//       - asset: fonts/google-icon.ttf
//
//
// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL ()
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//
import 'package:flutter/widgets.dart';

class CustomIcons {

  static const _kFontFam = 'Google Icon';
  static const String? _kFontPkg = null;

  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
